[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt",
  # Son durumda GUI'li opencv geldiyse kaldır ve headless'ı sabitle
  "pip uninstall -y opencv-python || true",
  "pip install --no-cache-dir opencv-python-headless==4.9.0.80"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
