# nixpacks.toml

[phases.install]
cmds = [
  
  "python -m ensurepip --upgrade || true",
 
  "python -m pip install --upgrade pip",
  
  "python -m pip install --no-cache-dir -r requirements.txt",
 
  "python -m pip uninstall -y opencv-python || true",
  "python -m pip install --no-cache-dir opencv-python-headless==4.11.0.86"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
