# nixpacks.toml
########################################
[phases.setup]
nixPkgs = ["python311Full"]           # pip + venv

########################################
[phases.install]
cmds = [
  # 1) İzole sanal-ortam
  "python -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",

  # 2) Tüm requirements (bağımlılıklarıyla) kur
  "/opt/venv/bin/python -m pip install --no-cache-dir -r requirements.txt",

  # 3) GUI’li OpenCV’leri sök
  "/opt/venv/bin/python -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless opencv-contrib-python-headless || true",

  # 4) Headless sürümü tek başına kur
  "/opt/venv/bin/python -m pip install --no-cache-dir --no-deps opencv-python-headless==4.9.0.80",

  # 5) Ultralytics'i bağımlılıksız kur (torch & opencv bizde)
  "/opt/venv/bin/python -m pip install --no-cache-dir --no-deps ultralytics==8.3.170",

  # 6) Hızlı smoke-test (modüller import edilemezse build fail)
  "/opt/venv/bin/python - <<'PY'\nimport importlib, sys\nmods=['numpy','cv2','torch','yaml','tqdm','requests']\nfailed=[m for m in mods if importlib.util.find_spec(m) is None]\nprint('Missing:', failed)\nif failed: sys.exit(1)\nPY"
]

########################################
[env]
NIXPACKS_PYTHON_VERSION = "3.11"

########################################
[start]
cmd = "bash -lc 'exec /opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port ${PORT:-8080}'"
